version: "2"
services:
  web:
    image: "nginx"
    networks:
      fancy:
        ipv4_address: 172.28.5.1
  web2:
    image: "nginx"
    networks:
      fancy:
        ipv4_address: 172.28.5.2

networks:
  fancy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
